/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Jireh Castillo
 */
public class ViewOperacion extends javax.swing.JFrame {

    /**
     * Creates new form viewOperacion
     */
    public ViewOperacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_numero_uno = new javax.swing.JLabel();
        jTF_numero_uno = new javax.swing.JTextField();
        jL_numero_dos = new javax.swing.JLabel();
        jTF_numero_dos = new javax.swing.JTextField();
        jB_suma = new javax.swing.JButton();
        jB_resta = new javax.swing.JButton();
        jB_multiplicacion = new javax.swing.JButton();
        jB_division = new javax.swing.JButton();
        jB_modulo = new javax.swing.JButton();
        jB_limpiar = new javax.swing.JButton();
        jL_resultado = new javax.swing.JLabel();
        jTF_titulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_numero_uno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_numero_uno.setForeground(new java.awt.Color(0, 153, 153));
        jL_numero_uno.setText("Número 1");

        jL_numero_dos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_numero_dos.setForeground(new java.awt.Color(0, 153, 153));
        jL_numero_dos.setText("Número 2");

        jTF_numero_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_numero_dosActionPerformed(evt);
            }
        });

        jB_suma.setBackground(new java.awt.Color(51, 0, 153));
        jB_suma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_suma.setForeground(new java.awt.Color(255, 255, 255));
        jB_suma.setText("+");
        jB_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sumaActionPerformed(evt);
            }
        });

        jB_resta.setBackground(new java.awt.Color(51, 0, 153));
        jB_resta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_resta.setForeground(new java.awt.Color(255, 255, 255));
        jB_resta.setText("-");
        jB_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_restaActionPerformed(evt);
            }
        });

        jB_multiplicacion.setBackground(new java.awt.Color(51, 0, 153));
        jB_multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_multiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jB_multiplicacion.setText("*");
        jB_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_multiplicacionActionPerformed(evt);
            }
        });

        jB_division.setBackground(new java.awt.Color(51, 0, 153));
        jB_division.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_division.setForeground(new java.awt.Color(255, 255, 255));
        jB_division.setText("/");
        jB_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_divisionActionPerformed(evt);
            }
        });

        jB_modulo.setBackground(new java.awt.Color(51, 0, 153));
        jB_modulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_modulo.setForeground(new java.awt.Color(255, 255, 255));
        jB_modulo.setText("%");
        jB_modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_moduloActionPerformed(evt);
            }
        });

        jB_limpiar.setBackground(new java.awt.Color(255, 204, 0));
        jB_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jB_limpiar.setText("Limpiar");
        jB_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limpiarActionPerformed(evt);
            }
        });

        jL_resultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_resultado.setForeground(new java.awt.Color(255, 0, 102));
        jL_resultado.setText("Resultado:");

        jTF_titulo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTF_titulo.setForeground(new java.awt.Color(102, 102, 255));
        jTF_titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_titulo.setText("OPERACIONES BÁSICAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jB_suma)
                        .addGap(31, 31, 31)
                        .addComponent(jB_resta)
                        .addGap(27, 27, 27)
                        .addComponent(jB_multiplicacion)
                        .addGap(18, 18, 18)
                        .addComponent(jB_division))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_numero_uno)
                            .addComponent(jL_numero_dos))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_numero_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_numero_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jB_modulo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_limpiar)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jL_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
            .addComponent(jTF_titulo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTF_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_numero_uno)
                    .addComponent(jTF_numero_uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_numero_dos)
                    .addComponent(jTF_numero_dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jL_resultado)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_suma)
                    .addComponent(jB_resta)
                    .addComponent(jB_multiplicacion)
                    .addComponent(jB_division)
                    .addComponent(jB_modulo))
                .addGap(18, 18, 18)
                .addComponent(jB_limpiar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_numero_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_numero_dosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_numero_dosActionPerformed

    private void jB_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_restaActionPerformed
        
    }//GEN-LAST:event_jB_restaActionPerformed

    private void jB_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limpiarActionPerformed
         this.jL_resultado.setText("");
        this.jTF_numero_uno.setText("");
        this.jTF_numero_dos.setText("");
    }//GEN-LAST:event_jB_limpiarActionPerformed

    private void jB_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_multiplicacionActionPerformed
        
    }//GEN-LAST:event_jB_multiplicacionActionPerformed

    private void jB_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_divisionActionPerformed
       
    }//GEN-LAST:event_jB_divisionActionPerformed

    private void jB_moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_moduloActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jB_moduloActionPerformed

    private void jB_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sumaActionPerformed
     
    }//GEN-LAST:event_jB_sumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_division;
    public javax.swing.JButton jB_limpiar;
    public javax.swing.JButton jB_modulo;
    public javax.swing.JButton jB_multiplicacion;
    public javax.swing.JButton jB_resta;
    public javax.swing.JButton jB_suma;
    public javax.swing.JLabel jL_numero_dos;
    public javax.swing.JLabel jL_numero_uno;
    public javax.swing.JLabel jL_resultado;
    public javax.swing.JTextField jTF_numero_dos;
    public javax.swing.JTextField jTF_numero_uno;
    private javax.swing.JTextField jTF_titulo;
    // End of variables declaration//GEN-END:variables
}
